SHELL := /bin/bash
CC=gcc

CFLAGSPLPLOT= $(CFLAGS) -fPIC -Wall -g -O2 -Wextra ${INCDIRS}

all : plplot.so

plplot.o : plplot.c
	$(CC) -c $(CFLAGSPLPLOT) plplot.c -o plplot.o
plplot.so : plplot.o
	gcc -shared -o plplot.so plplot.o

distclean: clean
	rm Makefile

clean:
	rm -f *.o plplot.$(SOEXT)

check:
	@echo "not available"

install: all
	mkdir -p $(PACKSODIR)
	cp plplot.$(SOEXT) $(PACKSODIR)

installcheck:
	swipl -g test -t halt prolog/plplot_test.pl